apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: mynamespace
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: devopsinsiders/netflix-clone

        ports:
        - containerPort: 80
